[package]
name = "identity-cloud-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
identity = { git = "https://github.com/iotaledger/identity.rs", branch = "main", features = [
    "account",
] }
rocket = "0.5.0-rc.1"
rocket_okapi = { version = "0.8.0-alpha-1", features = ["swagger"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.5", features = ["full"] }
url = "2.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
