[default]
ident = "ica2"
#key_seed = "BHyHWQqKvvgbcGoXiGS33iUu1Q4KGKP4pJK11RNWzr8c"
#did_key = "did:key:z6LSgPAyaBFBaEDkUVdN68WRDVZJevc1nNi9G675oK1NsEXN"
#did_iota = "did:iota:As1FSRYahR2JYi3EyvWan43pLrnjGLkDffwQDcBf545G"
wallet_path = "/wallet/ica2.wallet.hold"
wallet_password = "changeme"
webhook_url = "http://webhook:1080"

[release]
address = "0.0.0.0"
port = 8090
ext_hostname = "http://localhost:8090"
ext_service = "http://localhost:8090"