[default]
ident = "identity-cloud-agent"

stronghold_path = "account-stronghold.hodl"
password = "changeme"

[debug]
port = 8000
ext_hostname = "http://localhost:8000"

[release]
address = "0.0.0.0"
port = 8080
