[default]
ident = "identity-cloud-agent"

stronghold_path = "account-stronghold.hodl.example"
password = "changeme"
endpoint = "http://localhost:8000"
webhook_url = "http://localhost:8000"
key_seed = "CLKmgQ7NbRw3MpGu47TiSjQknGf2oBPnW9nFygzBkh9h"
sign_key_seed = "At8xLdhdBEPHkK9X9J6pyePZxD6KTMJuTCSFhnAfPpDn"
# did = "did:key:z6MkpFZ86WuUpihn1mTRbpBCGE6YpCvsBYtZQYnd9jcuAUup"
did = "did:iota:HcFFrR72GJq2hXuwbz2UwE7wkDE2VRkX2NwHeSVroeUH"

[debug]
port = 8000
ext_hostname = "http://localhost:8000"

[release]
address = "0.0.0.0"
port = 8080
