[default]
ident = "identity-cloud-agent"
key_seed = "BHyHWQqKvvgbcGoXiGS33iUu1Q4KGKP4pJK11RNWzr8c"
did_key = "did:key:z6LSgPAyaBFBaEDkUVdN68WRDVZJevc1nNi9G675oK1NsEXN"
did_iota = "did:iota:As1FSRYahR2JYi3EyvWan43pLrnjGLkDffwQDcBf545G"
wallet_path = "wallet.hold.example"
wallet_password = "changeme"
webhook_url = "http://localhost:8000"

[debug]
port = 8000
ext_hostname = "http://localhost:8000"
ext_service = "http://localhost:8000"

[release]
address = "0.0.0.0"
port = 8080
ext_hostname = "http://localhost:8000"
ext_service = "http://localhost:8000"