[default]
ident = "identity-cloud-agent"
key_seed = "F1HNoGf2TCapigNMR6bcZYvUW3HZTFL7eUMXnciQeHhE"
did_key = "did:iota:ELp2hhmcZqRTJp6M9PXYonZ8e9WVjqE9bG55S5BJPhih"
did_iota = "did:iota:ELp2hhmcZqRTJp6M9PXYonZ8e9WVjqE9bG55S5BJPhih"
wallet_path = "wallet.hold.example"
wallet_password = "changeme"
webhook_url = "http://localhost:1080"

[debug]
port = 8000
ext_hostname = "http://localhost:8000"
ext_service = "http://localhost:8000"

[release]
address = "0.0.0.0"
port = 8080
ext_hostname = "http://localhost:8000"
ext_service = "http://localhost:8000"